### ISSUE TITLE
Using G.T. (Base) filter 

### ISSUE THREAD

**Issue by gino2014** [KingIsulgard/Magento-Noble-Extended-Order-Grid#1]
First of all i would like to say thank you for this usefull extension. We recognized an issue by using G.T. (Base) filter. If we add an amount by searching oders with amount like from 35 to 100 we will have been thrown out of the magento backend an see only an error page with the logfile number. 
Attached i poste the content of the file.
P.S. after disableing the extension the order grid works fine again.
P.P.S we are using magento 1.9.2.4 with all patches and PHP 5.6.30

Thanks in advance
Gino

a:5:{i:0;s:706:"SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'grand_total' in where clause is ambiguous, query was: SELECT COUNT(*) FROM `sales_flat_order_grid` AS `main_table`
 INNER JOIN `sales_flat_order` AS `sfo` ON sfo.entity_id=`main_table`.entity_id
 INNER JOIN `sales_flat_order_address` AS `sfoba` ON sfoba.parent_id=`main_table`.entity_id and sfoba.address_type = "billing"
 INNER JOIN `sales_flat_order_address` AS `sfosa` ON sfosa.parent_id=`main_table`.entity_id and sfosa.address_type = "shipping"
 INNER JOIN `sales_flat_order_payment` AS `sfop` ON sfop.parent_id=`main_table`.entity_id WHERE (`main_table`.`shipping_name` LIKE '%gino%') AND (`grand_total` >= '15' AND `grand_total` <= '40')";i:1;s:5132:"#0 /html/magento/lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#1 /html/magento/app/code/core/Zend/Db/Statement.php(291): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#2 /html/magento/lib/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /html/magento/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT COUNT(*)...', Array)
#4 /html/magento/lib/Varien/Db/Adapter/Pdo/Mysql.php(504): Zend_Db_Adapter_Pdo_Abstract->query('SELECT COUNT(*)...', Array)
#5 /html/magento/lib/Zend/Db/Adapter/Abstract.php(828): Varien_Db_Adapter_Pdo_Mysql->query(Object(Varien_Db_Select), Array)
#6 /html/magento/lib/Varien/Data/Collection/Db.php(225): Zend_Db_Adapter_Abstract->fetchOne(Object(Varien_Db_Select), Array)
#7 /html/magento/lib/Varien/Data/Collection.php(225): Varien_Data_Collection_Db->getSize()
#8 /html/magento/lib/Varien/Data/Collection.php(211): Varien_Data_Collection->getLastPageNumber()
#9 /html/magento/lib/Varien/Data/Collection/Db.php(522): Varien_Data_Collection->getCurPage()
#10 /html/magento/lib/Varien/Data/Collection/Db.php(569): Varien_Data_Collection_Db->_renderLimit()
#11 /html/magento/app/code/core/Mage/Adminhtml/Block/Widget/Grid.php(533): Varien_Data_Collection_Db->load()
#12 /html/magento/app/code/community/Noble/AdminOrderGrid/Block/Sales/Order/Grid.php(120): Mage_Adminhtml_Block_Widget_Grid->_prepareCollection()
#13 /html/magento/app/code/core/Mage/Adminhtml/Block/Widget/Grid.php(626): Noble_AdminOrderGrid_Block_Sales_Order_Grid->_prepareCollection()
#14 /html/magento/app/code/core/Mage/Adminhtml/Block/Widget/Grid.php(632): Mage_Adminhtml_Block_Widget_Grid->_prepareGrid()
#15 /html/magento/app/code/core/Mage/Core/Block/Abstract.php(922): Mage_Adminhtml_Block_Widget_Grid->_beforeToHtml()
#16 /html/magento/app/code/core/Mage/Core/Block/Abstract.php(641): Mage_Core_Block_Abstract->toHtml()
#17 /html/magento/app/code/core/Mage/Core/Block/Abstract.php(585): Mage_Core_Block_Abstract->_getChildHtml('grid', true)
#18 /html/magento/app/code/core/Mage/Adminhtml/Block/Widget/Grid/Container.php(77): Mage_Core_Block_Abstract->getChildHtml('grid')
#19 /html/magento/app/design/adminhtml/default/default/template/widget/grid/container.phtml(36): Mage_Adminhtml_Block_Widget_Grid_Container->getGridHtml()
#20 /html/magento/app/code/core/Mage/Core/Block/Template.php(241): include('/html/magento/a...')
#21 /html/magento/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#22 /html/magento/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#23 /html/magento/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#24 /html/magento/app/code/core/Mage/Adminhtml/Block/Widget/Container.php(308): Mage_Adminhtml_Block_Template->_toHtml()
#25 /html/magento/app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Adminhtml_Block_Widget_Container->_toHtml()
#26 /html/magento/app/code/core/Mage/Core/Block/Text/List.php(43): Mage_Core_Block_Abstract->toHtml()
#27 /html/magento/app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Core_Block_Text_List->_toHtml()
#28 /html/magento/app/code/core/Mage/Core/Block/Abstract.php(641): Mage_Core_Block_Abstract->toHtml()
#29 /html/magento/app/code/core/Mage/Core/Block/Abstract.php(585): Mage_Core_Block_Abstract->_getChildHtml('content', true)
#30 /html/magento/app/design/adminhtml/default/default/template/page.phtml(74): Mage_Core_Block_Abstract->getChildHtml('content')
#31 /html/magento/app/code/core/Mage/Core/Block/Template.php(241): include('/html/magento/a...')
#32 /html/magento/app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#33 /html/magento/app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#34 /html/magento/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#35 /html/magento/app/code/core/Mage/Core/Block/Abstract.php(923): Mage_Adminhtml_Block_Template->_toHtml()
#36 /html/magento/app/code/core/Mage/Core/Model/Layout.php(555): Mage_Core_Block_Abstract->toHtml()
#37 /html/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(390): Mage_Core_Model_Layout->getOutput()
#38 /html/magento/app/code/core/Mage/Adminhtml/controllers/Sales/OrderController.php(95): Mage_Core_Controller_Varien_Action->renderLayout()
#39 /html/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_Sales_OrderController->indexAction()
#40 /html/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('index')
#41 /html/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#42 /html/magento/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#43 /html/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#44 /html/magento/index.php(83): Mage::run('', 'store')
#45 {main}";s:3:"url";s:87:"/index.php/admin/XXXX/sales_order/index/key/f081d36fe56d1d7a7b7237aa6f943f57/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:5:"admin";}

**Comment by KingIsulgard** [comment]
Hi there, too bad about the error.

Sometimes this happens with number fields, once you try to filter the
column you can't use these form for the session.

Just change the column to a text field and it Will work just as Well.

Op 11 mrt. 2017 12:42 p.m. schreef "gino2014" <notifications@github.com>:
